services:
  n8n:
    build: .
    container_name: n8n_windsurf
    restart: unless-stopped
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - WEBHOOK_URL=http://localhost:5679/

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
